spring.application.name=balance
server.port=8090

spring.data.redis.host=redis
spring.data.redis.port=6379
spring.data.redis.password=${REDIS_PASSWORD}

spring.cache.redis.time-to-live=1800000

db.write.url=${DB_WRITE_URL}
db.read.urls=${DB_READ_1_URL},${DB_READ_2_URL}

db.pool.write.max-size=100
db.pool.write.min-idle=5

db.pool.read.max-size=20
db.pool.read.min-idle=5

spring.datasource.username=${POSTGRES_USER}
spring.datasource.password=${POSTGRES_PASSWORD}


# JPA Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true


# Initialize with sample data
spring.jpa.defer-datasource-initialization=true
spring.sql.init.mode=always

management.endpoints.web.exposure.include=health,prometheus,metrics
management.endpoint.prometheus.enabled=true
management.metrics.export.prometheus.enabled=true
management.metrics.tags.application=${spring.application.name}
management.metrics.tags.instance=${HOSTNAME}