spring.application.name=balance
server.port=${SERVER_PORT}

#spring.datasource.url=${SPRING_DATASOURCE_URL}

db.write.url=${DB_WRITE_URL}
db.read.urls=${DB_READ_1_URL},${DB_READ_2_URL}

spring.datasource.username=${POSTGRES_USER}
spring.datasource.password=${POSTGRES_PASSWORD}


# JPA Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true


# Initialize with sample data
spring.jpa.defer-datasource-initialization=true
spring.sql.init.mode=always