global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'api-servers'
    static_configs:
      - targets: ['api-server-1:8090', 'api-server-2:8090', 'api-server-3:8090']
    metrics_path: '/actuator/prometheus'