events {}

http {
    upstream spring_api{
        least_conn;
        server api-server-1:8090;
        server api-server-2:8090;
        server api-server-3:8090;
    }

    server {
        listen 80;
        location / {
            proxy_pass http://spring_api;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }
    }
}